### ISSUE TITLE
Add support for trailling comma for method paramerts

### ISSUE THREAD

**Issue by astronom** [nette/php-generator#106]
Since the last update trailing comma supports for constructor property promotion. Also support for arrays. But there is no support for method and function parameters. 

See https://github.com/nette/php-generator/blob/master/src/PhpGenerator/Printer.php#L322 Var `special` is determined dynamically

Suggest to add some parameter to `Printer` and support trailing comma whether needed.

**Comment by dg** [comment]
Oh, that's a bug in the code, it was supposed to print trailing comma every time.

**Comment by astronom** [comment]
I instal the version with fix and it is working! 
But in dev-master now is trailing whitespace in comment... 
When are youg going to release?

**Comment by astronom** [comment]
I suppose this will fix trailing whitespace in multiline comments https://github.com/nette/php-generator/pull/107
