### ISSUE TITLE
Promoted properties & reflection consistency

### ISSUE THREAD

**Issue by jkuchar** [nette/php-generator#113]
We have built [grifart/caffolder](https://github.com/grifart/scaffolder) on top of php-generator. As we need to also read the state from php-generator I have found an inconsistency with php-reflection.

With php reflection you get properties & promoted properties when retrieving `$class->getProperties()`. However when using php generator one has to use `$class->getProperties()` for old-style properties and `$class->getMethod('__construct')->getParameters()`. See [this](https://github.com/grifart/scaffolder/blob/b5d413efe76546b4ef6066479e5fe87a3861231d/src/Capabilities/CapabilityTools.php#L27-L39) utils method for more info.

Wouldn't it be nicer to have property accessible directly using `$class->getProperties()`?

**Comment by dg** [comment]
It would be a BC break, I don't really want to deal with it.

**Comment by JanTvrdik** [comment]
Also it does not make sense to me. PhpGenerator internal structure is AST-like, meaning it corresponds to the code structure, not to the code meaning. So for example PHP reflection will also return methods from traits, but PhpGenerator will not.
