### ISSUE TITLE
Extractor does not extract enum method body using EnumType::from() and withBodies: true

### ISSUE THREAD

**Issue by sisklu** [nette/php-generator#115]
Version: 4.0.3

### Bug Description
When using `EnumType::from` with argument `withBodies` set to `true`, the extracted enum method has no body.

### Steps To Reproduce
```PHP
<?php

require_once __DIR__ . "/vendor/autoload.php";

enum Color
{
	case Red;
	case Blue;
	case Green;

	public function getColor(): string
	{
		return $this->name;
	}
}

echo \Nette\PhpGenerator\EnumType::from('Color', withBodies: true);
```
gives
```PHP
enum Color
{
	case Red;
	case Blue;
	case Green;

	public function getColor(): string
	{
	}
}
```

### Expected Behavior
```PHP
enum Color
{
	case Red;
	case Blue;
	case Green;

	public function getColor(): string
	{
		return $this->name;
	}
}
```

### Possible Solution
Condition here in Extractor
https://github.com/nette/php-generator/blob/ce449138b73ee788e818afeb41af51df3ec03710/src/PhpGenerator/Extractor.php#L69
should also check if node is instance of `Node\Stmt\Enum_`.

**Comment by dg** [comment]
Can you send PR?

**Comment by dg** [comment]
Can you send PR?
