### ISSUE TITLE
`PhpFile::fromCode` does not respect raw code (unstructured)

### ISSUE THREAD

**Issue by niconoe-** [nette/php-generator#127]
Version: 4.0.5

### Bug Description
When using `Nette\PhpGenerator\PhpFile::fromCode()` on a PHP snippet that does not contain any structure (no class, no function, no interface, no enum, …), the rending is losing every piece of code.

### Steps To Reproduce
Run:
```php
$foo = PhpFile::fromCode(<<<XX
    <?php
    // This is a comment
    return [
        'foo' => 5,
        'bar' => 8,
    ];
    XX);
echo $foo;
```
### Actual Behavior
Displays
```
<?php

```

### Expected Behavior
Displays
```
<?php
// This is a comment
return [
    'foo' => 5,
    'bar' => 8,
];
```

### Possible Solution
Possibly all node should be detected by the `$visitor->callback` callable defined in the `Extractor::extractAll()`  method?

<hr>

Even if this is sometimes considered as a bad practice, some PHP files can contain `return …` and you can then get the value returned with a call on `require $myFile;`. This is pretty nice to manage extra ressource configuration files for instance.
In my case, I'm using this mecanism to load a configuration. I was trying to use `nette/php-generator` as I wish to programmatically make updates to my configuration file, meaning regenerate some PHP config files with updated data.

Anyway, thank you for your amazing work. Even if this is an issu, I will certainly use nette/php-generator for other purposes in the next weeks!

**Comment by dg** [comment]
This library was created mainly for class management, and it has no special API for the pure code, for example inside the methods. It's just a string. So I can't think of any use for loading this global code, because it would just be a string again.

**Comment by niconoe-** [comment]
Ok, I understand. Thanks a lot for your answer :slightly_smiling_face:
