### ISSUE TITLE
Using comment before for parameter throws exception 

### ISSUE THREAD

**Issue by ticktackk** [nette/php-generator#135]
When attempting to the following code:
```php
<?php

require 'vendor/autoload.php';

$file = \Nette\PhpGenerator\PhpFile::fromCode(<<<PHP
<?php

namespace Hello;

class World
{
    public function example(/** @noinspection  */?string \$example) :? string
    {
        return 'boo';
    }
}
PHP
);
```
I get an exception saying
> Value '/** @noinspection */ ?string' is not valid type.

That is because when parsing the parameter type for `$example`, this package doesn't clear the comment before attempting to get the parameter type.

Currently running 3.6.9.

**Comment by dg** [comment]
I don't know what you're doing that's throwing you an error.

**Comment by ticktackk** [comment]
I have updated the original message to give better explanation.
