### ISSUE TITLE
Nullable union type

### ISSUE THREAD

**Issue by GromNaN** [nette/php-generator#139]
From [PHPWatch: PHP 8.0: Union Types](https://php.watch/versions/8.0/union-types) 
> You can declare a type as nullable by prefixing a `?` sign to the type. For example, if a certain property can be a `string` or a `null`, you can declare it as `?string`. With PHP 8.0 Union Types, `string|null` will be functionally equivalent to `?string`.

Also, `?` is incompatible with union types. `?string|int` is not accepted.

I'd like modify [Type::nullable()](https://github.com/nette/php-generator/blob/8b728c622c49b196513c0f95508f2f66342d1e8f/src/PhpGenerator/Type.php#L86-L89) to detect  union type and add `|null` instead of `?`.

Alternatively, `Type::union()` could accept a 2nd parameter: `$nullable` that adds the `|null`

I'll create a PR if that sounds good for you.

Note: intersection types are not nullable, [RFC was declined](https://wiki.php.net/rfc/nullable_intersection_types).

**Comment by dg** [comment]
I agree, and I'll be glad for the PR
