### ISSUE TITLE
Breaking change within minor version bump RE: namespaces

### ISSUE THREAD

**Issue by Westie** [nette/php-generator#145]
Hello

I'm working on a project that uses anonymous classes with namespaces.

According to the Nette documentation, here's how this software package handles anonymous classes:

![](https://ss.westie.sh/7Kjbf)

Unfortunately it appears impossible to add an anonymous class to a file (and understandably so - where do you even start!)

However, in [commit bcb74f3](https://github.com/nette/php-generator/commit/bcb74f30affe6766adaeb363fb66cfeaad818238) a breaking change was introduced which meant that any attempts to generate a namespace definition, where that definition did not have any linked functions or classes, was to be omitted.

I've worked around this now, using the flag `Printer::$omitEmptyNamespaces` that was added as part of that commit, but this still leaves me in a position where I don't know if there'll be a future update that would change this behaviour in future.

I was wondering what the community's thoughts on this were?

**Comment by dg** [comment]
I don't understand what you're trying to accomplish. What are the *anonymous functions with namespaces*? How do it relate to anonymous classes? Can you give a specific example?

**Comment by Westie** [comment]
> What are the anonymous functions with namespaces

This is a brainfart, apologies.

As following the rest of the tone of this issue, It should read:

> What are the anonymous classes with namespaces

**Comment by Westie** [comment]
A real world example would be this:

```PHP
namespace X\Y;

use V\A;
use V\B;

return class extends A {
    function __construct(B $b) {
        ...
    }
}
```

Within Nette, there appears so far to be no way as to clean up generated anonymous classes. How I have to do it, is by creating an instance of `PhpFile`, create an instance of `PhpNamespace` and assign that to the file, associate any class or function references I want aliased, then print the file and the anonymous class manually and hope that they match up.

**Comment by dg** [comment]
Your example, that's *global code* that this library never supported. It only allows you to define classes and functions in namespaces. So I don't understand what the breaking change is. Did something stop working for you?

**Comment by Westie** [comment]
> that's _global_ code that this library never supported

Personally I wouldn't say that it is global code, as in my eyes it is an anonymous class that has been defined within the context of a namespace.

But, having thought about it I believe I can see (and I think more importantly, _follow_) why it is that your opinion is such, so that would explain the current behaviour.

> I don't understand what the breaking change is

The breaking change is the addition of `$omitEmptyNamespaces` to the Printer - as the anonymous class cannot be associated with the namespace (as it is by definition, not a class with a name) - any attempt to print the namespace will result in an empty namespace definition being generated.

> Did something stop working for you

Yes, that is correct. With `$omitEmptyNamespaces` being set to its default value of true, the Printer detected that there were no functions nor classes associated with that namespace, then decided to not print it.

**Comment by dg** [comment]
I'm sorry, but I don't understand what you want. If there is a bug, please post the code here that used to work and now doesn't. If the problem is that `$omitEmptyNamespaces` is true, change it to false, it's a public variable. Code outside of functions and classes is not (yet) supported by this library.

**Comment by Westie** [comment]
> Code outside of functions and classes is not (yet) supported by this library

I'll therefore deem it as not a bug then, just a rather quirky feature gap.
