### ISSUE TITLE
Broken Aliases

### ISSUE THREAD

**Issue by GameCharmer** [nette/php-generator#147]
Version: 4.1.2

### Bug Description
Implementing interfaces by alias results in those aliases being addressed as root.

### Steps To Reproduce
```php
$cNamespace = new PhpNamespace('GCWorld\\ORM\\Generated');
$cClass     = $cNamespace->addClass('ExampleClass');
$cNamespace->addUse('GCWorld\\ORM\\Abstracts\\DirectSingle', 'dbc');
$cNamespace->addUse('GCWorld\\ORM\\Interfaces\\GeneratedInterafce','dbi');
$cClass->setExtends('dbc');
$cClass->addImplement('dbi');

echo $cNamespace;
```

results in 
```php
namespace GCWorld\ORM\Generated;

use GCWorld\ORM\Abstracts\DirectSingle as dbc;
use GCWorld\ORM\Interfaces\GeneratedInterafce as dbi;

class ExampleClass extends \dbc implements \dbi
{
}
```

### Expected Behavior
The backslashes in extends and implements shouldn't exist.

**Comment by dg** [comment]
https://doc.nette.org/en/php-generator#toc-class-names-resolving

**Comment by GameCharmer** [comment]
I just updated from 4.0.5 to 4.1.2 and couldn't find any reference to this new "feature" in the release notes. /shrug

**Comment by dg** [comment]
This isn't a new feature, it's how it's worked since the beginning.

**Comment by GameCharmer** [comment]
This works in 4.0.5 without the leading slashes, but fails catastrophically in 4.1.2

```php
$cNamespace = new PhpNamespace('GCWorld\\ORM\\Generated');
$cClass     = new ClassType('ExampleClass', $cNamespace);
$cNamespace->addUse('GCWorld\\ORM\\Abstracts\\DirectSingle', 'dbc');
$cNamespace->addUse('GCWorld\\ORM\\Interfaces\\GeneratedInterafce','dbi');
$cClass->setExtends('dbc');
$cClass->addImplement('dbi');

$cPrinter  = new PsrPrinter();
$contents  = '<?php'.PHP_EOL;
$contents .= $cPrinter->printNamespace($cNamespace);
$contents .= $cPrinter->printClass($cClass);
// Write contents to file
```
Seems there was a backwards incompatible change somewhere in there.

**Comment by dg** [comment]
Well, that's a different code. I'll fix the behavior, for now you can use `$cPrinter->omitEmptyNamespaces = false;`
