### ISSUE TITLE
 PhpParser\Lexer\Emulative::__construct(): Argument #1 ($phpVersion) must be of type ?PhpParser\PhpVersion, array given

### ISSUE THREAD

**Issue by i0FFLINE** [nette/php-generator#149]
Version: 4.1.2

### Bug Description
the call does not match the constructor of the third-party package

### Steps To Reproduce
```php
$ns = new PhpNamespace("My\Namespace");
$target = ClassType::fromCode(file_get_contents('/path/to/class.php'));
```
class.php
```php
<?php
namespace My\Namespace;
class Foo {
}
```

### Expected Behavior
No exceptions

### Possible Solution
Look into
- `nette/php-generator/src/PhpGenerator/Extractor.php : 50` call
- `nikic/php-parser/lib/PhpParser/Lexer/Emulative.php : 38` constructor
 called in /absolute/path/to/vendor/nette/php-generator/src/PhpGenerator/Extractor.php on line 50`

**Comment by i0FFLINE** [comment]
nikic/php-parser : 5.0.0 released

**Comment by dg** [comment]
fixed
