### ISSUE TITLE
Add support for "Roave/BetterReflection"

### ISSUE THREAD

**Issue by WalterWoshid** [nette/php-generator#159]
Repo: https://github.com/Roave/BetterReflection

My use case:
For my library https://github.com/okapi-web/php-aop I need to create copies of classes and modify them. But I am not allowed to autoload them, I have to reflect them by the file contents itself. I actually hacked it together myself, by adding the BetterReflection classes as a union type.

For example:

```php
public function fromParameterReflection(\ReflectionParameter $from): Parameter
{...}
```

becomes

```php
use Roave\BetterReflection\Reflection\ReflectionParameter as BetterReflectionParameter;

public function fromParameterReflection(\ReflectionParameter|BetterReflectionParameter $from): Parameter
{...}
```

From my experience the BetterReflection library has all the methods that the Base Reflection classes also have. And it will work, even if people don't have the BetterReflection library installed.

**Comment by JanTvrdik** [comment]
Why don't use use the built-in [BetterReflection adapter](https://github.com/Roave/BetterReflection/blob/6.37.x/src/Reflection/Adapter/ReflectionParameter.php)?

**Comment by WalterWoshid** [comment]
@JanTvrdik Damn, I'm stupid. Thank you for the information!
