### ISSUE TITLE
AddConstant does not validate name.

### ISSUE THREAD

**Issue by SamMousa** [nette/php-generator#24]
- bug report? yes
- feature request?no
- version: v2.5.x-dev

### Description
Constant names are not validated resulting in invalid PHP files.

### Steps To Reproduce
````
$file = new \Nette\PhpGenerator\PhpFile();
$object = $file->addClass('Tester');
$object->addConstant('test-invalid-name', "value");
````

**Comment by dg** [comment]
Fixed
