### ISSUE TITLE
"Uses" and "Extend"

### ISSUE THREAD

**Issue by carono** [nette/php-generator#26]
- bug report? yes
- feature request? no
- version: 2.6

### Description
When you specify "uses", the class is not inherited correctly from the specified class, if they are partially matched and there is a difference in the registers.

### Steps To Reproduce
```php
$namespace = new PhpNamespace('app\models');
$namespace->addUse('Yii');
$class = $namespace->addClass('Demo');
$class->addExtend('yii\db\ActiveRecord');
echo "<?php\n\n".$namespace;
```

```php
<?php

namespace app\models;

use Yii;

class Demo extends Yii\db\ActiveRecord // <= Wrong namespace, expected yii\db\ActiveRecord
{
}
```

**Comment by dg** [comment]
Both `yii\db\ActiveRecord` and `Yii\db\ActiveRecord` will be resolved to `Yii\db\ActiveRecord`, or not? I.e. there is no difference.

**Comment by carono** [comment]
I expect the class to be `yii\db\ActiveRecord`, because it has nothing to do with the previously specified `Yii` and I specify this class directly in `$class->addExtend('yii\db\ActiveRecord');`. In this case, `yii\db\ActiveRecord` and `Yii\db\ActiveRecord` this is not the same thing.

**Comment by dg** [comment]
Look at this example https://3v4l.org/HkpSm, they are the same because PHP is case insensitive.

**Comment by carono** [comment]
Yes, I looked at the demo more closely, indeed, this is normal behavior, for me it's unexpected, I'm sorry for the trouble.
