### ISSUE TITLE
Missing support for importing namespaces in PhpFile

### ISSUE THREAD

**Issue by Nazariy** [nette/php-generator#38]
Seems like it's not possible to import namespaces via `Nette\PhpGenerator\PhpFile` for example:

```php
<?php
use My\Full\Classname as Another, My\Full\NSname;

$obj = new Another; // instantiates object of class My\Full\Classname
NSname\subns\func(); // calls function My\Full\NSname\subns\func
?>
```
http://php.net/manual/en/language.namespaces.importing.php

Currently it's only possible via PhpNamespace class

**Comment by duxthefux** [comment]
Jep seems like. 

+1 for that

**Comment by JanTvrdik** [comment]
Can't use just use `PhpNamespace` with empty namespace?

**Comment by duxthefux** [comment]
can you give an example? @JanTvrdik
