### ISSUE TITLE
Dumping an array variable does not use the Printer's overridden indentation

### ISSUE THREAD

**Issue by Jeroeny** [nette/php-generator#41]
php version: 7.3.0
nette/php-generator version: 3.2.1

### Bug Description
When adding a constant to a class as below
```
$map = [
    'foo' => 'bar',
    'example' => 'value',
];

$class
    ->addConstant('MAP', $map)
    ->setVisibility(ClassType::VISIBILITY_PROTECTED);
```
it results in:
```
    protected const MAP = [
	'foo' => 'bar',
	'example' => 'value',
    ];
```
When printing with `Nette\PhpGenerator\PsrPrinter`.

### Expected Behavior
The constant printed with PsrPrinter's 4 spaces indentation instead of tabs. 

### Possible Solution
The tab is hardcoded at https://github.com/nette/php-generator/blob/master/src/PhpGenerator/Helpers.php#L74. Could we change it so that we can pass the indentation to the helper?

**Comment by bckp** [comment]
You can use tabsToSpaces from helper if you want to indent with spaces instead of tabs...

**Comment by zeleznypa** [comment]
I'm also have this issue.

**Comment by Jeroeny** [comment]
@zeleznypa I've worked around this with:

```php
Nette\PhpGenerator\Helpers::tabsToSpaces($contents);
```
