### ISSUE TITLE
Newlines in set

### ISSUE THREAD

**Issue by frewinchristopher** [nette/php-generator#44]
Version: 3.2.2

### Bug Description
Is there any way to support newlines in the setBody() method? I've read through the documentation and issues here on GitHub, but didn't find anything. If it _is_ supported, an example in the README would be nice.

### Steps To Reproduce
Using `\n` in the setBody() string parameter results in a literal '\n' printed in that method's body.

### Expected Behavior
A new line should be in the method body.

### Possible Solution
Support for \n in the setBody() parameter.

**Comment by dg** [comment]
Simply use `->setBody("first line\nsecondline")`

**Comment by frewinchristopher** [comment]
Ah excellent, it was the combination of having to use double quotations "" to get \n to work!
