### ISSUE TITLE
How to remove traits from class parsed from reflection?

### ISSUE THREAD

**Issue by 6562680** [nette/php-generator#53]
This is damn awesome work with this library, you saved my life.

Not sure i would need it, but really - there's no deleteTrait() method inside ClassType, currently i made some static facades for my services, and not sure, what if i add some traits to my services - will it be inside created class.

Anyway, THANK YOU.

--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

* Nette Forum: https://forum.nette.org
* Nette Gitter: https://gitter.im/nette/nette
* Slack (czech): https://pehapkari.slack.com/messages/C2R30BLKA

**Comment by dg** [comment]
I added `removeTrait()`

**Comment by 6562680** [comment]
Working.

Also its very hard for me to getMethods() and detect what methods was inherited from trait, and what from the class.
