### ISSUE TITLE
Nette\PhpGenerator\Parameter havent option/method to detect is Method parameter variadic

### ISSUE THREAD

**Issue by 6562680** [nette/php-generator#54]
Version: 3.3.3

### Bug Description
I tried to copy class using reflection then make some changes with method parameters, calling it through different method. So i join params using php native implode() function and failed, because i had some params variadic with ...$param definition in method signature.

I tried to check, but there's no method, will use php reflection method for that at now

**Comment by dg** [comment]
This is true, because variadic is not a parameter, but a function.

Try to use Printer::printParameters($function) instead of implode(). I changed it to public method in 3.3.4

**Comment by 6562680** [comment]
Will do

**Comment by 6562680** [comment]
I'd tested.
printParameters() prints method declaration parameters with types.

it is useless if i need print method body like sprintf('%s->method(%s), $class, $printer->printParameters($method));

Is there a way to do it somehow?

**Comment by dg** [comment]
I don't understand well what you want to achieve?

**Comment by 6562680** [comment]
```
$method->setBody(sprintf('static::getInstance()->%s%s', $method->getName(), $printer->printParameters($method));
```

**Comment by dg** [comment]
I understand. 

What parameters you pass on the functions are not *much related* to their reflection, it is purely up to you. implode() is here a good way.

**Comment by 6562680** [comment]
Would be great to see "isVariadic()" on parameter() too, to avoid manual Reflection (because you doing it already)
