### ISSUE TITLE
Feature request: Make spacing between class properties configurable

### ISSUE THREAD

**Issue by Jeroeny** [nette/php-generator#60]
I've noticed that `v3.4.0` contains the following change: `Printer: one-line properties without comments are not separated using one empty line`. 

In our codebase we have a code standard where we do have an empty line between properties, regardless of there being a comment or not. Now of course I understand that everyone has their own standards. 

So maybe it could be nice if this value is configurable, just like [`linesBetweenMethods`](https://github.com/nette/php-generator/blob/master/src/PhpGenerator/Printer.php#L27). So we can override it in our Printer. 

I hope this is something that can be considered. If it is, I'd be happy to contribute a PR.

**Comment by dg** [comment]
Fixed, I added $lineBetweenProperties
