### ISSUE TITLE
Make space between closing method parentheses and colon configurable

### ISSUE THREAD

**Issue by merlindiavova** [nette/php-generator#63]
Our coding standards enforces a space after the closing method parentheses and the proceeding colon.
It would super advantageous if this space could be configurable and honored in the `printReturnType` method.

Currently we have to manually go to all generated files and apply the spacing. As you can imagine this is very monotonous. I'm sure many others could also benefit from this.

I would super happy to contribute a PR if this is taken into consideration.

**Comment by dg** [comment]
You can now create your custom printer:

```
class MyPrinter extends Nette\PhpGenerator\Printer
{
	public function __construct()
	{
		$this->returnTypeColon = ' : ';
	}
}

**Comment by merlindiavova** [comment]
Amazing! Thank you for your prompt action and response!
