### ISSUE TITLE
How to use ->setType('OtherClass') within the same namespace

### ISSUE THREAD

**Issue by accgit** [nette/php-generator#64]
Version: 3.4.0

### Bug Description

The class then with a backslash reports that the class was not found if you have the same namespace.

### Steps To Reproduce
Generates this: 
`public \OtherClass $class`

### Expected Behavior
But in the same namespace I need this:
`public OtherClass $class;`

**Comment by JanTvrdik** [comment]
Call `setType` with fully qualified name.

**Comment by accgit** [comment]
@JanTvrdik thank you very much!
