### ISSUE TITLE
generate class property with default null value

### ISSUE THREAD

**Issue by elcheco** [nette/php-generator#70]
Version: v3.4.1

### Bug Description
I would need to generate class property with default value `null`, for example:
```

class XX {

    protected ?bool $myAttribute = null;

    protected ?int $myNumber = null;

}

```

### Steps To Reproduce
because the Property is by default set to null, it's not possible to set null as ->setValue(). I tried to use Literal('null'), but it also didn't work...

### Expected Behavior
Because of the change in php7.4 - set or null, it would be nice to have the possibility to set also null as the default value because then you avoid exceptions in the old code that the property is not set... 

If you use the unsigned property in the getter, in php7.3 return null it's fine and in 7.4 it throws an exception - property used before it was signed. Assigning `null` in the constructor helps to fix it.

In some cases, this saves some time and there's time for refactoring of the old code...

### Possible Solution
Maybe through the literal or some constant?

**Comment by dg** [comment]
```php
$class->addProperty('list')
	->setType('array')
	->setNullable()
	->setInitialized(); // for PHP 7.4
```

**Comment by elcheco** [comment]
It works! Thank you ;-)
