### ISSUE TITLE
Printer handles null value of Property as no value incorrectly 

### ISSUE THREAD

**Issue by dakur** [nette/php-generator#71]
Version: 3.4.1

### Bug Description
When printing class, there is this line:

```php
($property->getValue() === null && !$property->isInitialized() ? '' : ' = ' . $this->dump($property->getValue(), strlen($def) + 3)) // 3 = ' = '
```

which basically means that if I set value of `Property` to `null` intentionally, this value is not printed.

### Steps To Reproduce
E.g. `$property->setPrivate()->setValue(null)` generates `private $property;`  
But `$property->setPrivate()->setValue('test')` generates `private $property = 'test';` properly

### Expected Behavior
It should generate `private $property = null;`

### Possible Solution
Mark null state with some constant instead of `null`. So it would look something like this:

```php
class Property
{
    public const NO_DEFAULT_VALUE = '$73aad02e-7f5a-4ef2-8cdd-0fd09e6d9863§'; // hopefully no one is going to pass this string as default value

    // ...
}

// in printer:
($property->getValue() === Property::NO_DEFAULT_VALUE && !$property->isInitialized() ? '' : ' = ' . $this->dump($property->getValue(), strlen($def) + 3)) // 3 = ' = '
```

**Comment by dg** [comment]
use setInitialized()

**Comment by dakur** [comment]
@dg So you mean that this `setInitialized` is here to bypass this nullability problem?

**Comment by dg** [comment]
Yes, because PHP calls them *initialized* https://www.php.net/manual/en/reflectionproperty.isinitialized.php.

They only make sense if the property has a type, otherwise `= null` is unnecessary.

**Comment by dg** [comment]
But it is true that an explicit setValue (null) could call setInitialized() 🤔

**Comment by dakur** [comment]
Yes, that was actually the point of the issue – API did not work in the way developer expected and did not throw any error on usage either.

The fix solves this, thanks. 👍
