### ISSUE TITLE
Missing possibility to add variadic parameter to a method

### ISSUE THREAD

**Issue by TimWerdin** [nette/php-generator#76]
Simple example:
```
$method = $class->addMethod('count')
                ->addParameter('entities')
                ->setType('object ...');
```
Would result in the following:
```
function count(object ... $entities)
{
}
```

The space between the variadic operator `...` and the variable name `$entities` is not allowed by PSR12 standard.
A method like `setVariadic(bool $state = true): self;` on the `Nette\PhpGenerator\Parameter` could help with that.

**Comment by dg** [comment]
Use setVariadic() on method.

**Comment by TimWerdin** [comment]
Ok thank you. Would not have expected that on the method as the parameter is a variadic and not the method. But good that it is possible.

**Comment by dg** [comment]
If you can sent PR to documentation, it would be best. 

https://github.com/nette/docs/blob/doc-3.1/en/php-generator.texy
