### ISSUE TITLE
Load a class from a file template 

### ISSUE THREAD

**Issue by fnash** [nette/php-generator#79]
Hello
Thank you for this lib and its well designed api.

Is it possible to load a class from a file?

This could avoid loading a class in the current namespace to use reflection.
It could make php tools based on this library possible. Like refactoring tool.
The usecase here is to manipulate files wherever they are, independently from the current execution context.

Something like `Factory::fromClassFile`

Thanks

**Comment by dg** [comment]
Yeah, this could be implemented. I would appreciate it if you could [support this project](https://github.com/sponsors/dg).
