### ISSUE TITLE
Add possibility to use constants in attributes

### ISSUE THREAD

**Issue by leprz** [nette/php-generator#81]
Hi,
Is it possible to add support for constants in attributes arguments?
 
So generated code may look like this:
```
#[Argument('name', type: ArgumentTypes::REQUIRED)]
```
Currently it is possible to do something like [code below] or just use const value:
```php
$class->setAttribute(
    'Argument', 
    [
        'name',
        'type' => 'ArgumentTypes::REQUIRED'
    ]
);
```
in the result a constant will be wrapped in the quotes and treated as a string
```
#[Argument('name', type: 'ArgumentTypes::REQUIRED')]
```

I believe this feature will be highly demanded as more and more libs and frameworks are adding support for PHP 8 attributes. And they already use constants.

**Comment by mabar** [comment]
`new Nette\PhpGenerator\PhpLiteral('ArgumentTypes::REQUIRED')` should do the trick.

**Comment by leprz** [comment]
Thanks @mabar 🥇 It works. I should read documentation more carefully there is a chapter about Literals.
