### ISSUE TITLE
Update project description and readme.md

### ISSUE THREAD

**Issue by jkuchar** [nette/php-generator#9]
Currently it is not easy to figure out what is this project about.

**Comment by dg** [comment]
Will you send PR?

**Comment by jkuchar** [comment]
I have no clue what is this project about. :-/

**Comment by dg** [comment]
It generates PHP classes ([source](https://github.com/nette/php-generator/blob/master/tests/PhpGenerator/ClassType.phpt) [dest](https://github.com/nette/php-generator/blob/master/tests/PhpGenerator/ClassType.expect)).
