### ISSUE TITLE
Add ability to define trait import PHPDoc

### ISSUE THREAD

**Issue by InvisibleSmiley** [nette/php-generator#90]
In order to use generic traits with current versions of PHPStan, PHPDoc with @use must be added to trait imports (use).

AFAICS this generator is currently unable to define PHPDoc comments for trait imports.

FTR the feature was added to PHPStan here:
https://github.com/phpstan/phpstan-src/commit/87669234363d89252583664ef71309d5d8d3c7c1

**Comment by dg** [comment]
Can you describe it better?

**Comment by InvisibleSmiley** [comment]
Example code:
```php
<?php
$namespace = new \Nette\PhpGenerator\PhpNamespace('Foo');
$class = $namespace->addClass('Bar')->addTrait('SomeTrait');
$file = new \Nette\PhpGenerator\PhpFile();
$file->addNamespace($namespace);
echo (new \Nette\PhpGenerator\Printer())->printFile($file);
```

Result:
```php
<?php

namespace Foo;

class Bar
{
        use \SomeTrait;
}
```

Desired result:
```php
<?php

namespace Foo;

class Bar
{
        /** @use \SomeTrait<\Carbon\CarbonImmutable> */
        use \SomeTrait;
}
```

Trait for use case:
```php
<?php
/** @template T of \DateTimeInterface */
trait SomeTrait
{
    /** @return T */
    public function createDate(): \DateTimeInterface
    {
        return \Carbon\CarbonImmutable::now();
    }
}
```

**Comment by dg** [comment]
I understand you want to add a comment to "use" statement?

**Comment by dg** [comment]
The ideal would be something like

```php
 $namespace->addClass('Bar')
	->addTrait('SomeTrait')
	->addComment('@use \SomeTrait<\Carbon\CarbonImmutable>');
```

but `addTrait()` returns static and to change that would be a big BC break…

Maybe add a new method `useTrait()`...

**Comment by InvisibleSmiley** [comment]
I'd rather say adapt addTrait to accept either a string (behavior like now) or a class that can wraps the name and PHPDoc, like so:
```php
$trait = new PhpTrait('SomeTrait')->addComment('@use \SomeTrait<\Carbon\CarbonImmutable>');
$namespace->addClass('Bar')->addTrait($someTrait)
```

**Comment by dg** [comment]
It's working now. I added the `true` parameter and then it returns the `TraitUse` object:

```php
$namespace->addClass('Bar')
	->addTrait('SomeTrait', true)
		->addComment('@use \SomeTrait<\Carbon\CarbonImmutable>');
```
