### ISSUE TITLE
Attributes are not loaded correctly

### ISSUE THREAD

**Issue by alanpoulain** [nette/php-generator#98]
Version: 3.6.4

### Bug Description
When loading from the code (`PhpFile::fromCode($content)`), attribute arguments are not loaded as expected: arguments are "duplicated".
For instance, with this attribute:
```php
#[AnAttribute(foo: 'bar')]
```
The loaded arguments will be:
```php
$args = ['foo' => new Literal("foo: 'bar'")];
```

### Expected Behavior
The loaded arguments should be:
```php
$args = ['foo' => new Literal("'bar'")];
```

### Possible Solution
The issue comes from the call to `getReformattedContents` which gets everything inside the attribute as raw. It shouldn't be the case when loading content.

**Comment by alanpoulain** [comment]
Thanks!

**Comment by dg** [comment]
You're welcome
